### ISSUE TITLE
UE4 Editor crashed after 'make launch'

### ISSUE THREAD

**Issue by zzhzz4429** [HARPLab/DReyeVR#109]
Hi there,
 The UE4 editor gave me this error after 'make launch'. Does anyone know how to solve it?
<img width="303" alt="image" src="https://user-images.githubusercontent.com/82368221/234647703-50cd3e37-dea5-47e2-b14a-4bf7fd4feb8e.png">

**Comment by GustavoSilvera** [comment]
Please see #90 to verify you are on the supported version of UE4

**Comment by zzhzz4429** [comment]
> 

Problem solved.Thanks!
