### ISSUE TITLE
How to specify 2 arguments simultaneously for make import

### ISSUE THREAD

**Issue by Dreyevr** [HARPLab/DReyeVR#114]
In the carla documentation, there are 2 ways to execute make import
```
make import  ARGS="--package=<package_name>"
```
and
```
make import  ARGS="--no-carla-materials"
```
But how are you supposed to ingest a map with a custom name, and without carla materials at the same time?

**Comment by GustavoSilvera** [comment]
I believe just a space between the two arguments will work.

**Comment by Dreyevr** [comment]
After importing a map and opening it with the UE4editor, I am prompted with the message that 2 source files have changed and if i want to import them. 

One file is the "own_name_Package", while the other is config\roadpainter_decals and you're asked to choose dataTableRowType (see image below). Whatever i choose, i get the message that the JSON file failed to parse. We usually just ignore this, but I was wondering if this would have some effect at the quality of the textures or the performance in any way. 

Have you ever come across something like this?

**Comment by GustavoSilvera** [comment]
No, I have never seen this as I've only ever tested and used the original TownX maps from Carla

**Comment by FBanani** [comment]
> After importing a map and opening it with the UE4editor, I am prompted with the message that 2 source files have changed and if i want to import them.
> 
> One file is the "own_name_Package", while the other is config\roadpainter_decals and you're asked to choose dataTableRowType (see image below). Whatever i choose, i get the message that the JSON file failed to parse. We usually just ignore this, but I was wondering if this would have some effect at the quality of the textures or the performance in any way.
> 
> Have you ever come across something like this?
> 
> ![UE4_import](https://user-images.githubusercontent.com/126558520/238419236-6c3334a0-6791-4ef2-8f2a-0f3539df63bc.png)

Did you solve this issue. I have this problem. Also, in unreal engine nothing is shown?
Could you help me?

**Comment by elnazbanani** [comment]
> > After importing a map and opening it with the UE4editor, I am prompted with the message that 2 source files have changed and if i want to import them.
> > One file is the "own_name_Package", while the other is config\roadpainter_decals and you're asked to choose dataTableRowType (see image below). Whatever i choose, i get the message that the JSON file failed to parse. We usually just ignore this, but I was wondering if this would have some effect at the quality of the textures or the performance in any way.
> > Have you ever come across something like this?
> > ![UE4_import](https://user-images.githubusercontent.com/126558520/238419236-6c3334a0-6791-4ef2-8f2a-0f3539df63bc.png)
> 
> Did you solve this issue. I have this problem. Also, in unreal engine nothing is shown? Could you help me?

ffff
