### ISSUE TITLE
"Fatal Error" while using start_replaying.py

### ISSUE THREAD

**Issue by Nitro60zeus** [HARPLab/DReyeVR#119]
So i followed the format to play the .rec file, but it seems to crash. Here's the pic

![image](https://github.com/HARPLab/DReyeVR/assets/133999055/e9ad1dcf-6fdb-4c02-a297-ef66fdd80c00)

**Comment by anastaruno** [comment]
Hi! It is hard to determine the cause of the issue without any additional information. Could you please send the recording file so we can learn more? Meanwhile, try running 'make check' from your DReyeVR directory to ensure it is installed correctly.

**Comment by Nitro60zeus** [comment]
Hi! Herein i have attached the .rec file in zip format. Lemme know if there's any issues.

[exp_a1_test_06_09_2023_12_39_33.zip](https://github.com/HARPLab/DReyeVR/files/11724516/exp_a1_test_06_09_2023_12_39_33.zip)

For sure, I shall run `make check` and update you asap.

**Comment by Nitro60zeus** [comment]
Update: `make check` was successful. No issues.

**Comment by Nitro60zeus** [comment]
Any update?

**Comment by shh1v** [comment]
After getting the fatal error, could you upload the file $CARLA_ROOT$/Unreal/CarlaUE4/Saved/Logs/CarlaUE4.log here?

**Comment by Nitro60zeus** [comment]
[CarlaUE4.log](https://github.com/HARPLab/DReyeVR/files/12051364/CarlaUE4.log)

Hey, thanks for your response! Here's the file.

**Comment by Nitro60zeus** [comment]
Removed and installed again, and this time I made sure to run script using x64 Native Tools CMD prompt. Worked.
