### ISSUE TITLE
getting fatal error

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#121]
I have worked with DReyeVR but know I got this error. Also, I got the fatal error and crash when I executed CarlaUE4.exe or CarlaUE4.exe -vr
Assertion failed: PlayerInputComponent != nullptr [File:C:\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR\DReyeVRPawn.cpp] [Line: 593] 

0x00007ffb62fdfe7c KERNELBASE.dll!UnknownFunction []
0x00007ffad10096a6 UE4Editor-Core.dll!ReportAssert() [C:\UnrealEngine-carla\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformCrashContext.cpp:1616]
0x00007ffad100d039 UE4Editor-Core.dll!FWindowsErrorOutputDevice::Serialize() [C:\UnrealEngine-carla\Engine\Source\Runtime\Core\Private\Windows\WindowsErrorOutputDevice.cpp:78]
0x00007ffad0d2548d UE4Editor-Core.dll!FOutputDevice::LogfImpl() [C:\UnrealEngine-carla\Engine\Source\Runtime\Core\Private\Misc\OutputDevice.cpp:61]
0x00007ffad0ca9f15 UE4Editor-Core.dll!AssertFailedImplV() [C:\UnrealEngine-carla\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
0x00007ffad0cac1d0 UE4Editor-Core.dll!FDebug::CheckVerifyFailedImpl() [C:\UnrealEngine-carla\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
0x00007ffaed943c19 UE4Editor-CarlaUE4.dll!ADReyeVRPawn::SetupEgoVehicleInputComponent() [C:\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR\DReyeVRPawn.cpp:593]
0x00007ffaed93d5a6 UE4Editor-CarlaUE4.dll!ADReyeVRPawn::BeginEgoVehicle() [C:\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR\DReyeVRPawn.cpp:89]
0x00007ffaed95ef2e UE4Editor-CarlaUE4.dll!ADReyeVRLevel::FindEgoVehicle() [C:\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR\LevelScript.cpp:85]
0x00007ffaed95e64f UE4Editor-CarlaUE4.dll!ADReyeVRLevel::BeginPlay() [C:\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR\LevelScript.cpp:53]
0x00007ffab91f8d1c UE4Editor-Engine.dll!AActor::DispatchBeginPlay() [C:\UnrealEngine-carla\Engine\Source\Runtime\Engine\Private\Actor.cpp:3517]
0x00007ffaba5ce21b UE4Editor-Engine.dll!AWorldSettings::NotifyBeginPlay() [C:\UnrealEngine-carla\Engine\Source\Runtime\Engine\Private\WorldSettings.cpp:248]
0x00007ffab9945d51 UE4Editor-Engine.dll!AGameStateBase::HandleBeginPlay() [C:\UnrealEngine-carla\Engine\Source\Runtime\Engine\Private\GameStateBase.cpp:205]
0x00007ffaba573e0e UE4Editor-Engine.dll!UWorld::BeginPlay() [C:\UnrealEngine-carla\Engine\Source\Runtime\Engine\Private\World.cpp:4349]
0x00007ffab996831d UE4Editor-Engine.dll!UGameInstance::StartPlayInEditorGameInstance() [C:\UnrealEngine-carla\Engine\Source\Runtime\Engine\Private\GameInstance.cpp:483]
0x00007ffacc513226 UE4Editor-UnrealEd.dll!UEditorEngine::CreateInnerProcessPIEGameInstance() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:2941]
0x00007ffacc535f3e UE4Editor-UnrealEd.dll!UEditorEngine::OnLoginPIEComplete_Deferred() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1503]
0x00007ffacc513f03 UE4Editor-UnrealEd.dll!UEditorEngine::CreateNewPlayInEditorInstance() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1750]
0x00007ffacc551cca UE4Editor-UnrealEd.dll!UEditorEngine::StartPlayInEditorSession() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:2711]
0x00007ffacc555151 UE4Editor-UnrealEd.dll!UEditorEngine::StartQueuedPlaySessionRequestImpl() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1116]
0x00007ffacc554a18 UE4Editor-UnrealEd.dll!UEditorEngine::StartQueuedPlaySessionRequest() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\PlayLevel.cpp:1019]
0x00007ffacbfab19f UE4Editor-UnrealEd.dll!UEditorEngine::Tick() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1623]
0x00007ffacc8d3746 UE4Editor-UnrealEd.dll!UUnrealEdEngine::Tick() [C:\UnrealEngine-carla\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:426]
0x00007ff740e39909 UE4Editor.exe!FEngineLoop::Tick() [C:\UnrealEngine-carla\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4836]
0x00007ff740e510ec UE4Editor.exe!GuardedMain() [C:\UnrealEngine-carla\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
0x00007ff740e511ca UE4Editor.exe!GuardedMainWrapper() [C:\UnrealEngine-carla\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
0x00007ff740e64e5d UE4Editor.exe!WinMain() [C:\UnrealEngine-carla\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
0x00007ff740e67ba6 UE4Editor.exe!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
0x00007ffb645126bd KERNEL32.DLL!UnknownFunction []
0x00007ffb6582a9f8 ntdll.dll!UnknownFunction []
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/4d1b394d-62ef-48e2-a1c1-51d05799011a)
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/d71bd23b-609f-457c-b8db-9be118f52a13)
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/f39eb916-572d-4023-a881-99a372c1509b)

**Comment by shh1v** [comment]
Are you using the latest DReyeVR release? Because I cant trace back your error.
