### ISSUE TITLE
make package not working for the UnrealCarla fork

### ISSUE THREAD

**Issue by shuckerino** [HARPLab/DReyeVR#122]
Hello,

in the command summary of the installation process, it states: "Rather than https://github.com/CarlaUnreal/UnrealEngine UE4, you SHOULD clone https://github.com/HARPLab/UnrealEngine"

After trying to clone the UnrealEngine fork from the link, it says that the repository is not found. I have also tried to make it work with the normal carla patch for UnrealEngine, but there I get errors with namespaces when executing "make `package".

Glad if anyone could help!

Errors when executing make package:

` 
  ERROR: Failed to build "D:/CarlaDReyeVR/Unreal_CARLA_Patch/Engine/Programs/AutomationTool/Saved\UATTempProj.proj":
         D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(17,15): error CS0234: Der Typ- oder Namespacename "Management" ist im Namespace "Windows" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.) [D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
         D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,24): error CS0246: Der Typ- oder Namespacename "IAsyncOperationWithProgress<,>" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
         D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,52): error CS0246: Der Typ- oder Namespacename "DeploymentResult" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
         D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLensPlatform.Automation.cs(1228,70): error CS0246: Der Typ- oder Namespacename "DeploymentProgress" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis). [D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Source\Programs\AutomationTool\HoloLens\HoloLens.Automation.csproj]
  
         (see D:\CarlaDReyeVR\Unreal_CARLA_Patch\Engine\Programs\AutomationTool\Saved\Logs\Log.txt for full exception trace)
  AutomationTool exiting with ExitCode=1 (Error_Unknown)
  BUILD FAILED
  
  -[Package]: [ERROR] There was a problem while packaging Unreal project.
            [ERROR] Please read the screen log for more information.
  make: *** [package] Fehler 1`
`

**Comment by shh1v** [comment]
Its https://github.com/GustavoSilvera/UnrealEngine

**Comment by shuckerino** [comment]
Ah, thanks a lot!

**Comment by shuckerino** [comment]
When I run Setup.bat it gives me following error:

Checking dependencies...
Updating dependencies:   0% (0/63485)...
Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-12245497-69c6ab0ca64f438392018dc810d1ad84/017c812ca5e91e3dceac600c163aa6735873919e': Remote server returned an error: (403) Forbidden. (WebException)

I guess this has something to do with this https://forums.unrealengine.com/t/upcoming-disruption-of-service-impacting-unreal-engine-users-on-github/1155880 ?

I have not found any other solution to resolve this error...

**Comment by shuckerino** [comment]
> When I run Setup.bat it gives me following error:
> 
> Checking dependencies... Updating dependencies: 0% (0/63485)... Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-12245497-69c6ab0ca64f438392018dc810d1ad84/017c812ca5e91e3dceac600c163aa6735873919e': Remote server returned an error: (403) Forbidden. (WebException)
> 
> I guess this has something to do with this https://forums.unrealengine.com/t/upcoming-disruption-of-service-impacting-unreal-engine-users-on-github/1155880 ?
> 
> I have not found any other solution to resolve this error...

Okay, I now just downloaded and replaced follwoing XML file and it works, hope it doesn't cause any errors later: 
https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/Commit.gitdeps.xml

**Comment by ALEX95GOGO** [comment]
> > When I run Setup.bat it gives me following error:
> > Checking dependencies... Updating dependencies: 0% (0/63485)... Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-12245497-69c6ab0ca64f438392018dc810d1ad84/017c812ca5e91e3dceac600c163aa6735873919e': Remote server returned an error: (403) Forbidden. (WebException)
> > I guess this has something to do with this https://forums.unrealengine.com/t/upcoming-disruption-of-service-impacting-unreal-engine-users-on-github/1155880 ?
> > I have not found any other solution to resolve this error...
> 
> Okay, I now just downloaded and replaced follwoing XML file and it works, hope it doesn't cause any errors later: https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/Commit.gitdeps.xml

I also met this problem. Does it work for you?

**Comment by shuckerino** [comment]
> > > When I run Setup.bat it gives me following error:
> > > Checking dependencies... Updating dependencies: 0% (0/63485)... Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-12245497-69c6ab0ca64f438392018dc810d1ad84/017c812ca5e91e3dceac600c163aa6735873919e': Remote server returned an error: (403) Forbidden. (WebException)
> > > I guess this has something to do with this https://forums.unrealengine.com/t/upcoming-disruption-of-service-impacting-unreal-engine-users-on-github/1155880 ?
> > > I have not found any other solution to resolve this error...
> > 
> > Okay, I now just downloaded and replaced follwoing XML file and it works, hope it doesn't cause any errors later: https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Build/Commit.gitdeps.xml
> 
> I also met this problem. Does it work for you?

Yes, replacing the XML file resolved this issue for me. For me it did not cause any related errors later.

**Comment by NGMSLab** [comment]
Hello, how've you solve the make `package error? I just encounter the same issue when make package.
