### ISSUE TITLE
I have got a new error while I want to make launch after making PythonAPI

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#124]
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/9c0e48b9-2685-49d5-a23b-769548d84b3b)
Hi @GustavoSilvera 
I want to install the DReyeVR and when I make launch afet making pythonAPI, I have got this error. Could you help me?
when I did this
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/6c511208-2296-44d5-bde5-e39ad89d02da)
I did not face that I issue
Thanks

**Comment by ajdroid** [comment]
What version of the dreyevr code are you using?

**Comment by FBanani** [comment]
I do not know.
Also I have another issue:
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/affdc83b-b158-4b7c-80d4-b4a1f319b108)
I run "python DReyeVR_logging.py," but when my experiment is finished, what should I do to collect the data? I mean, where is it saved?

**Comment by ajdroid** [comment]
Can you provide the full paths of your built package and the DReyeVRConfig file you are editing?

**Comment by FBanani** [comment]
thanks alot.
do you mean this:
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/122e068d-7f05-4a1f-bcd2-5562d34c965f)

**Comment by FBanani** [comment]
> thanks alot. do you mean this: ![image](https://user-images.githubusercontent.com/98695913/267061579-122e068d-7f05-4a1f-bcd2-5562d34c965f.png)

**Comment by FBanani** [comment]
> Can you provide the full paths of your built package and the DReyeVRConfig file you are editing?

Thanks a lot.
Do you mean this:
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/598c1115-a836-4151-816d-4d714321acc6)

**Comment by ajdroid** [comment]
If you want it to change in the package, you should modify the corresponding DReyeVRConfig. What is the path to the binary you are running that is built via make package?

**Comment by FBanani** [comment]
> This looks like the config file in the dreyevr source. If you want it to change in the package, you should modify the corresponding DReyeVRConfig. What is the path to the binary you are running that is built via make package?

I modify the code here and change the "DrawFlatReticle=False; reticle in flat-screen mode" to False. then in carla root I make a package.
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/1ead6bd5-ca01-4fe5-8a0d-7b0d8101d74f)

**Comment by FBanani** [comment]
> This looks like the config file in the dreyevr source. If you want it to change in the package, you should modify the corresponding DReyeVRConfig. What is the path to the binary you are running that is built via make package?

I am really sorry. I am not good at computer since I am civil engineer. In the DReyeVRConfig.h file I just change this line then in X64 in the carla root I execute make package.

**Comment by ajdroid** [comment]
In your `carla_root/Build\UE4Carla\0.9.13-*-*\WindowsNoEditor\CarlaUE4\Config` you will see the DReyeVRConfig file that you need to modify in order to make changes to your built version of DReyeVR. You do not need to re execute make package.

**Comment by FBanani** [comment]
> In your `carla_root\Build\UE4Carla\0.9.13-*-*\WindowsNoEditor\CarlaUE4\Config` you will see the DReyeVRConfig file that you need to modify in order to make changes to your built version of DReyeVR. You do not need to re execute `make package`.

Thank you so much.
Could you help me how to save the all simulator data as well.

**Comment by ajdroid** [comment]
Please read our docs: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#recordingreplaying-a-scenario

**Comment by FBanani** [comment]
> Please read our docs: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#recordingreplaying-a-scenario

Thanks but I saw in other issue "[How to acquire eye tracking data maybe in a better way?](https://github.com/HARPLab/DReyeVR/issues/81#top)
#81" GustavoSilvera mentioned used this code "python PythonAPI/examples/DReyeVR_logging.py" for gathering better eye gaze. Therefore, I overwhelmed.
Sorry for my basic question.

**Comment by FBanani** [comment]
> That is for getting eye tracking data in real time. If you just want to store the experiment to disk and replay or analyze it later, please use the resources in the Usage.md file.

thanks I found it in this directory:
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/27e8bea7-dfeb-4a8b-a58a-aed548e67d02)

is it correct

**Comment by ajdroid** [comment]
I just meant the resources documented in this link: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#recordingreplaying-a-scenario

**Comment by FBanani** [comment]
> I just meant the resources documented in this link: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#recordingreplaying-a-scenario

Thanks a lot.

**Comment by FBanani** [comment]
Hi @ajdroid  I come back with another question 
I execute python start_recording.py -n 0 in screen mode
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/a2744769-0db9-4334-854a-26f71def6c24)
then execute this
python show_recorder_file_info.py -a -f C:\test1.log > recorder.txt
then with DReyeVR-parse
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/bc1877d6-25e1-47a7-ab0f-cec43730769a)
show me this error. 
Also I have another issue when I run the following after python start_recording.py -n 0 during my experiment it gives me the self error.
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/a513053e-03b8-40a8-af51-7a3d21df862b)

**Comment by FBanani** [comment]
Hi @ajdroid I have another issue. However I am in VR mode it shows the gaze and pupil zero!!! COULD YOU HELP ME
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/57d0743e-3fec-4f4a-a9c5-bb5a26eaf67d)

**Comment by ajdroid** [comment]
Hi @FBanani please create a new issue if you have an unrelated problem to the main thread title. I am closing this issue.
