### ISSUE TITLE
Cannot connect with Steam VR

### ISSUE THREAD

**Issue by ALEX95GOGO** [HARPLab/DReyeVR#127]
Hi, I installed everything sucessfully. But when I launched Carla with ./CarlaUE4.exe -vr, and I opened steam VR but nothing is play there. I can also see the SRanipalRuntime works since the icon turns green. Do you have any suggestions? Thanks a lot!
![CarlaVR](https://github.com/HARPLab/DReyeVR/assets/12646722/2549c9e5-2c7c-45a1-9c62-7e6b99085942)

**Comment by ajdroid** [comment]
Can you use the UE4 editor to do a VR preview? Does that work?

**Comment by ALEX95GOGO** [comment]
Hi, I compiled the project in one pc and distribute it to another pc. For the pc I compiled I can do a VR preview, but for the pc I distributed it can open steam VR sometimes, but not always. Do you have any suggestions for this? Thanks a lot for your help!

**Comment by ALEX95GOGO** [comment]
I made a new account in Windows and this problem is solved. Maybe it's due to something wrong with my steam VR installation.
