### ISSUE TITLE
whether sumo-carla co-simulation is supported by DReyeVR

### ISSUE THREAD

**Issue by wx983** [HARPLab/DReyeVR#131]
Hi!
I wonder whether sumo-carla co-simulation is supported by DReyeVR or not. Thanks!

**Comment by wx983** [comment]
If not, what should I do to achieve sumo-carla co-simulation on DReyeVR?

**Comment by ajdroid** [comment]
This is not a functionality we have tested or intend to support. 
What happens when you try to run the default instructions?

**Comment by wx983** [comment]
Sorry, I mistaked python as python3. After change it, I succeeded in carla-sumo cosimulation.
