### ISSUE TITLE
getting Data From Simulator

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#135]
Hi @ajdroid  I come back with another question 
I execute python start_recording.py -n 0 in screen mode
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/a2744769-0db9-4334-854a-26f71def6c24)
then execute this
python show_recorder_file_info.py -a -f C:\test1.log > recorder.txt
then with DReyeVR-parse
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/bc1877d6-25e1-47a7-ab0f-cec43730769a)
show me this error. 
Also I have another issue when I run the following after python start_recording.py -n 0 during my experiment it gives me the self error.
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/a513053e-03b8-40a8-af51-7a3d21df862b)

**Comment by FBanani** [comment]
Hi @ajdroid I have another issue. However I am in VR mode it shows the gaze and pupil zero!!! COULD YOU HELP ME
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/57d0743e-3fec-4f4a-a9c5-bb5a26eaf67d)

**Comment by FBanani** [comment]
Hi @ajdroid 
I have another issue
I gathered data in Screen mode and VR mode: the number of frames and simulation time are as follows. 
![image](https://github.com/HARPLab/DReyeVR/assets/98695913/799f6d40-3f33-4112-a008-97fd94c28715)
As you see in screen mode the simulator updates around 3 times faster than VR mode.
Also, the root and environment in VR and Screen mode are same and the length of the road is about 2741 m having 45 seconds different is kind of weird!
Could you help me to improve my VR mode?
Thanks

**Comment by ajdroid** [comment]
The VR mode performance depends primarily on the GPU available to you and which mode you're using (are you launching the sim via `make launch` or `make package` then `CarlaUE4.exe -vr`
