### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by wx983** [HARPLab/DReyeVR#139]
![image](https://github.com/HARPLab/DReyeVR/assets/73030394/ee6b24da-4ab8-4d65-b8be-7319987b484d)
Hi! I don't see it while installing carla.

**Comment by wx983** [comment]
Or, is it ok to adopt the way of egg installation? In that case, I don't need to run that command to install wheel(whl).

**Comment by ajdroid** [comment]
What is in you `carla\dist` folder?

**Comment by wx983** [comment]
> What is in your `carla\dist` folder?

I don't have carla\dist folder. I'm installing CARLA before running `make pythonAPI`.

**Comment by ajdroid** [comment]
You should run make PythonAPI first to get the wheel
