### ISSUE TITLE
Driver starting position in the car change every time

### ISSUE THREAD

**Issue by ALEX95GOGO** [HARPLab/DReyeVR#141]
Hi, when I run in the VR mode, the driver starting position (orientation, position) is slightly different in the car every time I start Carla. Is there any way to make it consistent? Thanks a lot!

**Comment by ajdroid** [comment]
Hi, that should not be the case. The starting pose is set here: https://github.com/HARPLab/DReyeVR/blob/main/Config/DReyeVRConfig.ini
