### ISSUE TITLE
Third-person replay

### ISSUE THREAD

**Issue by ALEX95GOGO** [HARPLab/DReyeVR#146]
I saw your youtube video here: https://www.youtube.com/watch?v=yGIPSDOMGpY, I wonder how you can replay from a third person view?

**Comment by ajdroid** [comment]
You can pause a replay, possess the spectator and then use mouse and WASD to fly around.
Controls are specified here: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#replaying
