### ISSUE TITLE
Custom spawn point

### ISSUE THREAD

**Issue by StijnOosterlinck** [HARPLab/DReyeVR#148]
Hi,

How can i set a custom spawn point when spawning the DReyeVR vehicle?

I want to use this when I only need a certain section of a map (CARLA map or own map). Spawning the vehicle at a desired location is then more efficient than driving there every time from the default spawn point, but I can not find where exactly the spawn point is defined...

Thanks!

**Comment by ajdroid** [comment]
Hi -- you can achieve this by using [scenario runner ](https://github.com/carla-simulator/scenario_runner) (a core CARLA functionality) to define routes which start at your desired spawn point.

**Comment by StijnOosterlinck** [comment]
Thanks for the answer @ajdroid , but i'm not looking for specific routes, since the participant is allowed to 'freely' drive around.

It seems logical that a map would have a default spawn point, or is this defined when making the map in roadrunner?
If so, I would just want to change the default spawn point.

**Comment by ajdroid** [comment]
For Town 3 we specify spawn point in the DReyeVRConfig file. Otherwise we pick from spawn points in the map (see GetSpawnPoint in DReyeVRGameMode)
