### ISSUE TITLE
Version mismatch between client and simulator API

### ISSUE THREAD

**Issue by Wingspear** [HARPLab/DReyeVR#154]
I'm trying to run some examples under PythonAPI. I'm currently launching the simulator via "make launch" and running the scene through Unreal. Then, I'm running some example python scripts via the client API.

Even though my python client seems to be on 0.9.13 (as it was pulled from the right commit), the client is still interpreted as 0.9.14. Added some screenshots below. Any pointers?

<img width="745" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/c5ba3004-4c43-492c-8c27-077c20b522ef">

<img width="662" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/dd1950ed-9625-4400-81a7-78aafc06df9a">

**Comment by shh1v** [comment]
Can you list the files in your `$CARLA_ROOT$/PythonAPI/carla/dist` directory?

**Comment by Wingspear** [comment]
hmm.. I don't seem to have a `$CARLA_ROOT$/PythonAPI/carla/dist` directory listed.
<img width="470" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/ed59c3bf-1efd-4a1f-82ee-bef1686deaea">

**Comment by shh1v** [comment]
You are doing something wrong. The `make PythonAPI` should generate the egg and whl files. Are you running that command? Read the docs for installation.

**Comment by Wingspear** [comment]
After trying `make PythonAPI` again, the output logs that "the dist folder was installed successfully", but it doesn't look like the installation went through. It appears to be a linker error when trying to find the Boost library (we're using Python 3.8). I attached some screenshots below. Any ideas?

<img width="686" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/2ed8931c-390e-4586-ae40-6d72c8ee0057">
<img width="1259" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/de03eaf9-8e79-4025-8bf5-1d2c0897b92a">

**Comment by shh1v** [comment]
Yes, if there are linker errors when you first run `make PythonAPI`, rerunning the command shows success; however, those errors are still there. I am familiar with these errors. Please go through #46, and run the listed commands at the end.

Make sure to _first_ run `make clean` and get rid of **all** the files in your build folder.

**Comment by Wingspear** [comment]
I followed the instructions and reran `make PythonAPI`. After launching Unreal with `make launch` and running the `python generate_traffic.py` example, I'm still getting the same Client-Simulator version mismatch issue.
This is what my dist directory looks like:
<img width="414" alt="image" src="https://github.com/HARPLab/DReyeVR/assets/27274272/0bce236c-942a-44bc-914c-fe8064b6cec7">

**Comment by shh1v** [comment]
did you reinstall the new python whl file using `pip install carla-0.9.13...whl` file? Did you first run `pip uninstall carla`?

**Comment by Wingspear** [comment]
Awesome, `pip install carla-0.9.13...whl` did the trick. Thanks!
