### ISSUE TITLE
Triple Monitor

### ISSUE THREAD

**Issue by Nitro60zeus** [HARPLab/DReyeVR#155]
Hi all! Quick question. I want to use DReyeVR without VR but on a triple monitor display. Any advice on how to do that? Thanks a lot in advance.

**Comment by ajdroid** [comment]
You would have to use something like nDisplay: https://docs.unrealengine.com/4.26/en-US/WorkingWithMedia/nDisplay/
I would ask on the CARLA discord, I think someone has achieved this there -- it is non-trivial

**Comment by Nitro60zeus** [comment]
Understood! Thanks, man.
