### ISSUE TITLE
Import Additional Maps

### ISSUE THREAD

**Issue by Nitro60zeus** [HARPLab/DReyeVR#157]
Hi! 

how to import additional maps to DReyeVR? Like, the new updated maps from CARLA (eg Town 11, 12).

**Comment by ajdroid** [comment]
We only officially support upto Carla 0.9.13 and afaik the other towns are not supported to be built (via `make package`) in that CARLA version. If you can figure out how to include them in make package that should work for DReyeVR as well (probably you include it in `MapsToCook` in `Unreal/Carla/Config/DefaultGame.ini`
