### ISSUE TITLE
Eye tracing

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#160]
Hi @ajdroid,

I have a question about eye tracking. Is PlayStation VR2 compatible with DReyeVR? 
I am so sorry. I don't know much about the computer stuff. I saw a video that mentioned it use Tobii for eye tracing. 

![image](https://github.com/HARPLab/DReyeVR/assets/98695913/3e9b8e61-924c-4b0b-b879-c7d89b56d586)
 
Thank you in advance for your help.

**Comment by ajdroid** [comment]
It is not supported, sorry

**Comment by FBanani** [comment]
thanks. Do you know some VR headset with eye tracing? The "HTC Vive Pro Eye" is no longer produced.

**Comment by ajdroid** [comment]
Sorry no. It is no longer officially produced but you can still buy it on ebay

**Comment by FBanani** [comment]
Thanks.
