### ISSUE TITLE
How can I implement a head-up display on the windshield?

### ISSUE THREAD

**Issue by mqqq333** [HARPLab/DReyeVR#162]
Hello! How can I implement a head-up display on the windshield? It is about how to display information such as vehicle speed, navigation, speed limit, lane, etc. in real time on the car's windshield. Thank you very much.
![IMG_0187](https://github.com/HARPLab/DReyeVR/assets/101176458/4699aabd-5962-4e85-aebb-7114315eb0a0)

**Comment by shh1v** [comment]
Have you made any progress? I believe it may not be challenging to display dynamic driving task relevant information like speed limit, speed, lane; however, the navigation could be difficult. Are you seeking a way to display the route the driver is expected to reach the destination OR the expected route the (supposedly) automated vehicle will take, as CARLA does support automated driving? The implementation could vastly differ.
