### ISSUE TITLE
Idea of implementing hand tracking in DReyeVR

### ISSUE THREAD

**Issue by sunchongren** [HARPLab/DReyeVR#18]
Hi, 
did anyone consider implementing hand tracking in this program?
I am really interested in it and I am doing it right now.

**Comment by GustavoSilvera** [comment]
Hi @sunchongren I think hand tracking would be a fantastic addition to DReyeVR! 

Currently we have no plans on implementing it but there are plenty of reasons to include it, such as improving the user's sense of presence and increasing the number of potential interactions within the vehicle. While it is not our focus at the moment, we'd be happy to see what you come up with and integrate it with the rest of the codebase. 

If you have any questions regarding the codebase, we'll be happy to help.
