### ISSUE TITLE
How to disable the speed display?

### ISSUE THREAD

**Issue by aureliuszi** [HARPLab/DReyeVR#23]
![image](https://user-images.githubusercontent.com/25374562/166311244-beca1010-59f4-4fdb-b96a-69299e4fc257.png)

Hello friends! 

I'm wondering how to disable the red speed display on the right side. 

I have managed to disable the big red target and the FPS count by setting these variables in `C:\...\...\
CARLA_0.9.13-1-g8854804f4-dirty\WindowsNoEditor\CarlaUE4\Config` to false. I can't seem to find the speed display though. 

```
DrawFPSCounter=False; draw's FPS (frames per second) in top right corner of flat screen
DrawFlatReticle=False; reticle in flat-screen mode
```

**Comment by GustavoSilvera** [comment]
Hi @aureliuszi unfortunately you currently cannot disable them from the runtime params `DReyeVRConfig.ini`. 

However, you can disable them from modifying the source code and rebuilding. Specifically comment out the call to `ConstructDashText` in `EgoVehicle.cpp` (In the constructor) and the `UpdateDash` call in `EgoVehicle::Tick`.

This will ensure that the dash text (speedometer, gear indicator, and turn signals) never gets created and does not tick.

**Comment by aureliuszi** [comment]
To confirm, this involves opening `EgoVehicle.cpp` in the `C:\..\..\carla9.12\carla\Unreal\CarlaUE4\Source\CarlaUE4\DReyeVR` and rebuilding via `make carla CARLA=../carla `? 

There is another `EgoVehicle.cpp` in `C:\..\..\carla9.12\carla\Unreal\CarlaUE4\Intermediate\Build\Win64\CarlaUE4\Development\CarlaUE4`

**Comment by GustavoSilvera** [comment]
Correct, the intermediate files are effectively cache files that will get rewritten. So you never need to touch them.

**Comment by GustavoSilvera** [comment]
Also, you wouldn't need to `make Carla CARLA=../Carla`, you only need to `make launch` or `make package` once you edit the file within the Carla directory (as opposed to the DReyeVR directory)

**Comment by GustavoSilvera** [comment]
We recently added some documentation in the [FAQ page](https://github.com/HARPLab/DReyeVR/wiki/Frequently-Asked-Questions) on how to modify DReyeVR source once installed, which should answer some similar questions. 

Do you have any more updates with this issue that we should take care of?

**Comment by GustavoSilvera** [comment]
Due to lack of activity, we will close this. If there is another issue, feel free to reopen.
