### ISSUE TITLE
unreal engine

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#35]
After running make launch and loading the editor, when I dropdown menu I could not select V
![Screenshot (4)](https://user-images.githubusercontent.com/98695913/177356762-873bba0a-6c5e-463a-9fe0-5d2ef586fb43.png)
R
could you help me what I do wrong?

**Comment by GustavoSilvera** [comment]
Hi @FBanani, first off this looks like a vanilla Carla 0.9.13 install. So make sure to use DReyeVR content you run `make install` from the DReyeVR directory once (a bunch of files will copy over) and then go back to the Carla directory and run `make launch` there. (See [`install.md`](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Install.md) for more specifics). Once DReyeVR is installed you'll be placed in Town03 by default (so you'll know that its not vanilla carla). 

Then you should ensure that your headset is connected and active (yours looks asleep) while the UE4 editor is loading and you have the SteamVR plugin installed as described in [`SetupVR.md`](https://github.com/HARPLab/DReyeVR/blob/main/Docs/SetupVR.md). Then you should be able to select VR Preview. Or if all else fails you should be able to open the standalone packaged game (after `make package`) and add the flags `-vr` when you run `CarlaUE4.exe`. 

Hope this helps!

**Comment by FBanani** [comment]
thank you. I successfully update content
![image](https://user-images.githubusercontent.com/98695913/177388470-fa0f852a-d5d9-4c9e-86c9-293a8cced2d2.png)
but I have another issue
![Capture4](https://user-images.githubusercontent.com/98695913/177387921-103d3a52-0d9d-4ae9-933e-cec4645c522e.PNG)
when I copy make PythonAPI && make launch in "x64  Native Tools Command Prompt for VS 2019" it show me this error:
![image](https://user-images.githubusercontent.com/98695913/177388335-baa3313f-8839-462f-be10-acf82e08b48e.png)
what should I do?

**Comment by GustavoSilvera** [comment]
Try cleaning and rebuilding: `make clean && make PythonAPI`. And ensure the `zlib-source` directory is entirely removed before running `make PythonAPI` again. This is a Carla error, you haven't actually installed the DReyeVR content yet. 

Tip: if you don't need the PythonAPI yet, you can actually skip this step (as long as `make launch` works) and then continue with the instructions to install DReyeVR and then keep using the editor.

**Comment by FBanani** [comment]
I fixed it it is because of the different version of zlib
we have to change carla/Util/InstallersWin/install_zlib.bat and changing line 51 to "set ZLIB_VERSION=1.2.11" instead of "set ZLIB_VERSION=1.2.12
Thank you

**Comment by FBanani** [comment]
I have another issue 
![Capture5](https://user-images.githubusercontent.com/98695913/177410159-30207662-8393-4666-b0ee-79d74c8a8942.PNG)
I have the same issue as this one before and by adding "\" to environment in UE4_ROOT,  it was fixed. now after make PythonAPI && make launch I again find this issue, what should I do?

**Comment by FBanani** [comment]
I found a problem when I make PythonAPI, although it said successfully installed but it did not make dis folder in  PythonAPI\carla. I tried make clean then make PythonAPI for 3 times, but it does not make dist folder anytime. I copy the dist folder to PythonAPI\carla, it was made before when I install carla in windows. It is work but hopefully does not make problem in future!

**Comment by FBanani** [comment]
when I want to do "make install CARLA=../carla" in the "Windows x64 Native Tools Command Prompt for VS 2019":
![image](https://user-images.githubusercontent.com/98695913/177426218-ff05380d-9223-47ee-8547-a78c35937ea9.png)
I faced this issue, I do not know why?

**Comment by GustavoSilvera** [comment]
Okay can you try closing all UE4 instances (or rebooting) to fix the permission error. I think this because another application (probably UE4) has a lock on this file and Windows won't let you edit it live. 

I'm not sure about the compilation problem. Can you upload the entire build log?

**Comment by FBanani** [comment]
I restart my PC and it is work. thank you

**Comment by FBanani** [comment]
I want to make launch:
![image](https://user-images.githubusercontent.com/98695913/177564561-53c7c9b8-9aca-4c70-964f-03958734b27c.png)
the dist file is created:
![image](https://user-images.githubusercontent.com/98695913/177564742-958c5486-680d-447f-aa8c-b4ef2f0fe14b.png)
but I have an error:
![image](https://user-images.githubusercontent.com/98695913/177565567-bf85fbf4-445e-4b00-ae16-6c0a4367d3bc.png)

**Comment by GustavoSilvera** [comment]
Hi, based on a [similar issue](https://github.com/carla-simulator/carla/issues/2776) I think you need to define the UE4_ROOT environment variable since it appears to be missing. I'd recommend doing this by [creating a new environment variable](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10) called UE4_ROOT and assigning it the value of the folder where you installed UE4 (4.26 Carla fork) to.

**Comment by GustavoSilvera** [comment]
To elaborate further, you should have gone through [this installation page](https://carla.readthedocs.io/en/latest/build_windows/) to get Carla up and running. So make sure to follow the steps to get UE4 (Carla fork) installed properly.

**Comment by GustavoSilvera** [comment]
I'm going to assume this is resolved for the time being. Feel free to reopen if more questions come up.
