### ISSUE TITLE
adding other vehicle and changing Map

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#38]
Hi
I watch your YouTube video and I see that you added other vehicle and also other Map like Highway.
How can I bring Highway environment and add other vehicle?

**Comment by GustavoSilvera** [comment]
You can switch the maps and add vehicles into the scene by using the Carla PythonAPI as you would in normal Carla operation. For example see our modification to [start_recording.py](https://github.com/HARPLab/DReyeVR/blob/51ea84a65df001801f582051dc3899d996d3f7b9/PythonAPI/start_recording.py#L125-L134) (with `-n` random vehicles) and for specific programmable scenarios check out [scenario-runner](https://github.com/carla-simulator/scenario_runner) which is compatible with DReyeVR (Thats how we recorded that video).

**Comment by FBanani** [comment]
hi I execute python run_experiment.py --title "dreyevr_experiment" --route %SCENARIO_RUNNER_ROOT%\srunner\data\routes_debug.xml %SCENARIO_RUNNER_ROOT%\srunner\data\all_towns_traffic_scenarios1_3_4.json 0 
but I do not find a highway. it is just all towns. what should I do?

**Comment by GustavoSilvera** [comment]
There is a map with a highway (specifically Town04) that you should be able to spawn if you specify the right route in scenario runner. Perhaps @ajdroid can help more with that. 

Additionally, you can specifically *just* change the map with the PythonAPI by following [this guide](https://carla.readthedocs.io/en/latest/core_map/). 

Another option (if you want to avoid the PythonAPI altogether) is to change the default map from Town03 to Town04. This is pretty easy, just edit this the [DefaultEngine](https://github.com/HARPLab/DReyeVR/blob/main/Configs/DefaultEngine.ini#L11-L18) config file (in the Carla repo) and change all instances of `Town03` to `Town04`. 

You can also spawn NPC's pretty easily with the same PythonAPI guide.

**Comment by FBanani** [comment]
> There is a map with a highway (specifically Town04) that you should be able to spawn if you specify the right route in scenario runner. Perhaps @ajdroid can help more with that.
> 
> Additionally, you can specifically _just_ change the map with the PythonAPI by following [this guide](https://carla.readthedocs.io/en/latest/core_map/).
> 
> Another option (if you want to avoid the PythonAPI altogether) is to change the default map from Town03 to Town04. This is pretty easy, just edit this the [DefaultEngine](https://github.com/HARPLab/DReyeVR/blob/main/Configs/DefaultEngine.ini#L11-L18) config file (in the Carla repo) and change all instances of `Town03` to `Town04`.
> 
> You can also spawn NPC's pretty easily with the same PythonAPI

**Comment by wx983** [comment]
> There is a map with a highway (specifically Town04) that you should be able to spawn if you specify the right route in scenario runner. Perhaps @ajdroid can help more with that.
> 
> Additionally, you can specifically _just_ change the map with the PythonAPI by following [this guide](https://carla.readthedocs.io/en/latest/core_map/).
> 
> Another option (if you want to avoid the PythonAPI altogether) is to change the default map from Town03 to Town04. This is pretty easy, just edit this the [DefaultEngine](https://github.com/HARPLab/DReyeVR/blob/main/Configs/DefaultEngine.ini#L11-L18) config file (in the Carla repo) and change all instances of `Town03` to `Town04`.
> 
> You can also spawn NPC's pretty easily with the same PythonAPI guide.
After changing  all instances of `Town03 `to `Town04` in DefaultEngine.ini，the map is still not be changed. 
Do I need to rebuild DReyeVR? Or something else?

**Comment by wx983** [comment]
Something goes wrong with me. After revising and rebuilding, the map is still `Town3` and somtetimes I can't even run UE4 Editor vr mode. It either crashes after running or vr mode takes  no effects. But sometimes it runs no problems. That's really confusing.
To sum up, I just wonder how to change map to another not using pythonAPI.

**Comment by GustavoSilvera** [comment]
Are you trying to change the map in package/shipping mode? (CarlaUE4.exe -vr) If so you need to modify the `DefaultEngine.ini` file located in `%CARLA_ROOT%\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\Config\DefaultEngine.ini`.

In the editor mode you can **open** (CTRL+O) a Carla/Blueprints/Map file such as Town01-10HD and run in the editor this way. 

Do you have any logs for your crashes?

**Comment by wx983** [comment]
> 

I forget to save log files. I reinstall carla and DReyeVR. According to your words, it works! I have changed map `Town03` to `Town04` successfully both in Editor mode and in package/shipping mode. Thanks!

**Comment by wx983** [comment]
But after reinstalling, one log file is always generated in `C:\Users\%MY_USER_NAME%\AppData\Local\CarlaUE4\Saved\Logs` each time when I  `CarlaUE4.exe -vr`. I use SRanipal 1.3.3.0 rather than 1.3.6+ this time. **Although they exist, it runs no problems and functions well seemingly and just some minor openents are missing.**

![image](https://user-images.githubusercontent.com/73030394/218652011-1e4ae8bd-bb31-45c6-9a58-c741a9296ea9.png)

[CarlaUE4.log](https://github.com/HARPLab/DReyeVR/files/10729181/CarlaUE4.log)

**Comment by wx983** [comment]
By the way, do you know how to set to acquire the log file in the Editor mode? I can only find log files in package/shipping mode according to [this](https://forums.unrealengine.com/t/how-to-debug-shipping-build-exclusive-crash/411138/2) . I would appreciate it very much.

**Comment by wx983** [comment]
@GustavoSilvera Sorry, I forgot to @ you. So you didn't receive the e-mails.

**Comment by GustavoSilvera** [comment]
Hi, sorry yes I didn't get notifications so I'm sorry for not responding quickly. 
1. In the editor you can simply click `Window->Developer->Output Log` which should display the same CarlaUE4 log in real-time as you play in editor. 
2. Unfortunately I don't know of any good resources besides looking at basic UE4 tutorials and the Carla GitHub source code. There is the [main Carla documentation](https://carla.readthedocs.io/en/latest/) but that only gets you so far. 
3. Also, those `LogStreaming` errors can mostly be ignored since this seems to be a benign issue. You can try reinstalling the content by re-running the `Update.bat` (or `Update.sh` on Linux/Mac). 

Hope this helps!

**Comment by FBanani** [comment]
Sorry for the late reply. I got COVID and I could not open my eyes. Actually, when I changed the name of the maps in the DefaultEngine.ini, the map is changed in my editor as well as Carla's vanilla windows when I executed "CarlaUE4.exe -vr" and I have not faced this issue yet. Could you change your map with "world = client.load_world('Town03')"? If you could not you have to install Carla again and this issue is not related to the DReyeVR.

**Comment by wx983** [comment]
@GustavoSilvera @FBanani Thanks for your guys. No matter!

**Comment by wx983** [comment]
> Are you trying to change the map in package/shipping mode? (CarlaUE4.exe -vr) If so you need to modify the `DefaultEngine.ini` file located in `%CARLA_ROOT%\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\Config\DefaultEngine.ini`.
> 
> In the editor mode you can **open** (CTRL+O) a Carla/Blueprints/Map file such as Town01-10HD and run in the editor this way.
> 
> Do you have any logs for your crashes?

@FBanani 
Using this method, I can change my map successfully. I revised DefaultEngine.ini in `%CARLA_ROOT%\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\Config\DefaultEngine.ini` rather than `%DReyeVR_ROOT%\Configs\DefaultEngine.ini`

**Comment by wx983** [comment]
> 嗨，抱歉，是的，我没有收到通知，所以很抱歉没有迅速回复。
> 
> 1. 在编辑器中，您只需单击即可`Window->Developer->Output Log`实时显示与您在编辑器中玩游戏时相同的 CarlaUE4 日志。
> 2. 不幸的是，除了查看基本的 UE4 教程和 Carla GitHub 源代码外，我不知道有什么好的资源。有[主要的 Carla 文档](https://carla.readthedocs.io/en/latest/)，但仅此而已。
> 3. 此外，这些`LogStreaming`错误大多可以忽略，因为这似乎是一个良性问题。您可以尝试通过重新运行`Update.bat`（或`Update.sh`在 Linux/Mac 上）来重新安装内容。
> 
> 希望这可以帮助！

Hi, 
Recently, chatGPT is greatly popular with the world, I find it is a good way to ask it problems about carla!
