### ISSUE TITLE
Using conda for PythonAPI

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#39]
I am installing 2 times carla, one of them from their site the other from DReyeVR, which path you mean in this line?
![image](https://user-images.githubusercontent.com/98695913/177880978-fd77c898-3f59-442b-ae48-37731c808542.png)
I consider carla from DReyeVR as a desire path. I have done "make PythonAPI", should I "make clean" then again "make PythonAPI" before trying or not?

**Comment by GustavoSilvera** [comment]
I'm going to assume this is resolved for the time being. Feel free to reopen if more questions come up.
