### ISSUE TITLE
How to cook maps with local changes (adding signs)

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#44]
I want to insert something to the unreal engine (Town04) in Carla, but I work with windows! which is compatible with DReyeVR in windows can I make package?

**Comment by GustavoSilvera** [comment]
DReyeVR/Carla is compatible with Windows. I'm not sure what you want to insert and how you want to do it. The default towns (up to Town05) should already be installed when you run `make package`.

**Comment by FBanani** [comment]
> DReyeVR/Carla is compatible with Windows. I'm not sure what you want to insert and how you want to do it. The default towns (up to Town05) should already be installed when you run `make package`.

I want to add some signs to town04 and activate this signs in ReyeVR/Carla! this is my issue

**Comment by FBanani** [comment]
> DReyeVR/Carla is compatible with Windows. I'm not sure what you want to insert and how you want to do it. The default towns (up to Town05) should already be installed when you run `make package`.

for example: I want to add stop sign here
![image](https://user-images.githubusercontent.com/98695913/179549357-029d3bde-6a67-44c4-aad5-dcdcd8d63903.png)
then I 
![image](https://user-images.githubusercontent.com/98695913/179550239-088dff85-017b-4d0a-8d86-f5e275ca69ee.png)
because I work with windows
![image](https://user-images.githubusercontent.com/98695913/179550527-a6bf2ec8-af13-4142-91b8-a526e3d19c1f.png)
then I select CarlaUE4 folder after that what should I do? that is my question

**Comment by GustavoSilvera** [comment]
Also, in case you ever wanted to add custom signs at runtime through the PythonAPI. We have a [tutorial](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Signs.md) just for that!

**Comment by FBanani** [comment]
> * add the stop sign (like you already have)
> * save the map (ctrl + s)
> * (sanity check) you should be able to switch to another map and then come back to Town04 and see the stopsign you added in 1)
> * Close down the editor and run `make package` in the `carla` directory (This is Carla's way of packaging the project from the terminal with all the added libraries/assets)

thank you so much
