### ISSUE TITLE
Adding custom signs in the Carla world

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#47]
hi 
in your tutorial 
![image](https://user-images.githubusercontent.com/98695913/179795875-7aa4b08d-04d9-4cd3-9e47-34d16e13c534.png)
and when I want to open "[Content/Static/DefaultSign.jpg](https://github.com/HARPLab/DReyeVR/blob/main/Content/Static/DefaultSign.jpg)" it shows me this error
![image](https://user-images.githubusercontent.com/98695913/179808319-0b962b81-5118-4a4e-ab60-e170fa9a969c.png)

I have different file path!
my path is //NAS-SYNTHIA/synthia/CARLA_ART/Static/TrafficSigns/NoTurn/SM_noTurn_n.png and I do not understand where it is!
![image](https://user-images.githubusercontent.com/98695913/179795628-b7745780-bb2c-4a17-9491-fa15748ab2db.png)
could you help me?

**Comment by GustavoSilvera** [comment]
Whoops! Looks like that `.jpg` should actually be a `.png`. [Here](https://github.com/HARPLab/DReyeVR/blob/main/Content/Static/DefaultSign.png) is the correct link. Sorry about that!

**Comment by GustavoSilvera** [comment]
Yeah the `//NAS-SYNTHIA/synthia/CARLA_ART/Static/TrafficSigns/NoTurn/SM_noTurn_n.png` is not on your local machine because it is the cached path from where this art was created (on the Carla devs' team) so don't worry about that. 

You should be able to either overwrite or replace this asset with your own once you add your own sign texture.

**Comment by FBanani** [comment]
> Yeah the `//NAS-SYNTHIA/synthia/CARLA_ART/Static/TrafficSigns/NoTurn/SM_noTurn_n.png` is not on your local machine because it is the cached path from where this art was created (on the Carla devs' team) so don't worry about that.
> 
> You should be able to either overwrite or replace this asset with your own once you add your own sign texture.

thank you so much but I need to overwrite other signs with different shape and color. something like this
![image](https://user-images.githubusercontent.com/98695913/179845673-4b3a9fad-9c18-42c4-99b1-8bc5224efdf4.png)
therefore what should I do?

**Comment by GustavoSilvera** [comment]
Ok well first, I recommend you take a blank canvas sign from the sign with this shape you want (the one in the tutorial is a rounded rectangle so that won't work for you) then overlay this image over that texture (in GIMP or another image processing app, but we used GIMP)

Then compute the normals and import the rgb & normals images (textures) into UE4 and update the Texture parameter groups as shown in the tutorial. Then everything else should follow just like the tutorial

**Comment by FBanani** [comment]
thank you I have another question because of the different shape should I select different folder like  LaneReduct or noTurn is ok?

**Comment by GustavoSilvera** [comment]
Any sign/shape should be fine, just be sure to duplicate the folder if you don't want to overwrite the original files.

**Comment by FBanani** [comment]
hi I have another question about different sign
I want put message in this sign
![image](https://user-images.githubusercontent.com/98695913/180450766-b188d0a0-89b5-4667-8b39-a544850648c8.png)
and this is a folder of material
![image](https://user-images.githubusercontent.com/98695913/180451034-705c076a-b46d-4c33-a6c9-086ca951cc84.png)
I do not know how to change message
![image](https://user-images.githubusercontent.com/98695913/180451185-dc41ebfe-fc39-4955-947b-fab4542c1162.png)
could you help me?

**Comment by GustavoSilvera** [comment]
In this case you'll want to extract the PNG from the texture, open it in GIMP (or another image editing software) and modify the message exactly where the original is (the CAUTION stuff). 

We couldn't find an easier way than simply overlaying some text over the sign which works well enough for simple flat-coloured signs/text but might be harder for you since you are trying to edit a pretty unique sign.

**Comment by FBanani** [comment]
Thank you but it doesn’t show (the CAUTION stuff). I do not how to activate it!

**Comment by GustavoSilvera** [comment]
What do you mean? You should be able to simply screenshot the texture and import that screenshot into GIMP to do whatever you'd like to it. Once its in GIMP you can overlay some text onto it and save that into a new texture to replace this one.

**Comment by FBanani** [comment]
My problem is in the simulation it does not show anything but it should show CAUTION STUFF

**Comment by GustavoSilvera** [comment]
Can you send a screenshot. There was probably an issue when importing the texture into the editor and applying it to the new mesh.

**Comment by FBanani** [comment]
I am sorry I left the lab and can I send it tomorrow?
Thank you for your help

**Comment by FBanani** [comment]
I have another issue 
when I want to reimport
it shows me this:
Fatal error!
![Screenshot (9)](https://user-images.githubusercontent.com/98695913/180624699-fc0ba696-a283-4a3c-8220-1ba8618b0b98.png)
and closed the unreal engine I try it with the other signs and it does not happened.
I think in this area we could not change as before!
do you have any other solution

**Comment by GustavoSilvera** [comment]
Are you overwriting the existing content or did you duplicate it and are making your own custom sign?

Also if you think this is a problem with corrupted files you can rerun the `Update.sh` script to redownload all the vanilla Carla assets (then `make install` again to install the DRryeVR content over it)

**Comment by FBanani** [comment]
I have duplicated and making my own.
Before doing this I can check with Carla that I installed because I am not sure it is related to my installation of DReyeVR
Thank you so much

**Comment by FBanani** [comment]
in Carla I do not have problem with unreal engine but when I reimport it it shows me black things
![image](https://user-images.githubusercontent.com/98695913/180646156-cf1fe81c-4c8d-4ca3-99a7-581db506f69f.png)
in the material files there is no texture to allocate "_n" and "_d" files
![image](https://user-images.githubusercontent.com/98695913/180646524-93ab3e1a-9829-4906-8d68-fb6026f86209.png)
and in the file with suffix "_orm" what do I have to change? there is no where to allocate "M_"
![image](https://user-images.githubusercontent.com/98695913/180646346-b04cb71c-529b-4830-a656-59c51faba634.png)
also they start with "T_" not "SM_"!
![image](https://user-images.githubusercontent.com/98695913/180646098-757a5a52-9405-4a09-a758-45a9c4638b0d.png)

**Comment by FBanani** [comment]
> I have duplicated and maked my own. Before doing this I can check with Carla that I installed because I am not sure it is related to my installation of DReyeVR Thank you so much

in Carla I do not have problem with unreal engine but when I reimport it it shows me black things
![image](https://user-images.githubusercontent.com/98695913/180646156-cf1fe81c-4c8d-4ca3-99a7-581db506f69f.png)
in the material files there is no texture to allocate "_n" and "_d" files
![image](https://user-images.githubusercontent.com/98695913/180646524-93ab3e1a-9829-4906-8d68-fb6026f86209.png)
and in the file with suffix "_orm" what do I have to change? there is no where to allocate "M_"
![image](https://user-images.githubusercontent.com/98695913/180646346-b04cb71c-529b-4830-a656-59c51faba634.png)
also they start with "T_" not "SM_"!
![image](https://user-images.githubusercontent.com/98695913/180646098-757a5a52-9405-4a09-a758-45a9c4638b0d.png)

**Comment by GustavoSilvera** [comment]
You should be able to simply create a new texture with the .jpg's you created and that should not give you any problems. You'll need to make the normal (`_n`) and rgb textures and then there is a place to link them to the material (prefix `M_`) which can then be applied to your static mesh. 

I am not familiar with an `_orm` suffix texture, maybe it has something to do with lighting/shading. You'll have to look into that more.
