### ISSUE TITLE
Eye Tracker crosshair still showing when SRanipal is disabled

### ISSUE THREAD

**Issue by shh1v** [HARPLab/DReyeVR#55]
How can I remove the red crosshair when SRanipal is disabled, or just remove It completely (because I am not using it)?

**Comment by ajdroid** [comment]
You want to toggle `DrawFlatReticle` or `DrawSpectatorReticle` depending on whether or not you want it off in replay vs VR spectator mode
https://github.com/HARPLab/DReyeVR/blob/51ea84a65df001801f582051dc3899d996d3f7b9/Configs/DReyeVRConfig.ini#L83

**Comment by shh1v** [comment]
Thank you!
