### ISSUE TITLE
installing Carla

### ISSUE THREAD

**Issue by FBanani** [HARPLab/DReyeVR#70]
Hi, I want to install DReyeVR in another computer but now I have a huge problem with installation of Carla that never see before. is there any way to install DReyeVR without installation of Carla.
please help me 
thank you

**Comment by GustavoSilvera** [comment]
No, DReyeVR is an extension of Carla that uses Carla for the base architecture. It is necessary to build Carla before building DReyeVR.

**Comment by FBanani** [comment]
thank you
