### ISSUE TITLE
can not find frame capture images in Unreal/CarlaUE4/{FrameDir}/{DateTimeNow}/{FrameName}* executing 'python start_replaying.py -f C:\Users\11\AppData\Local\CarlaUE4\Saved\test1.log'

### ISSUE THREAD

**Issue by wx983** [HARPLab/DReyeVR#80]
Hi~  Long time no see. How are you? I have a new issue.
Executing `CarlaUE4.exe -vr` from x64 cmd on windows and `python start_replaying.py -f /PATH/TO/RECORDING/FILE # windows`(in my computer is `python start_replaying.py -f C:\Users\11\AppData\Local\CarlaUE4\Saved\test1.log),`  I can't find the resulting frame capture images in Unreal/CarlaUE4/{FrameDir}/{DateTimeNow}/{FrameName}*. And I can only see images two days ago, which were generated in Editor mode, I remember. That's a little bit strange.
![image](https://user-images.githubusercontent.com/73030394/218316237-1f7bd4f4-5314-4702-9420-54e713129c39.png)

By the way, I verify **RunSyncReplay** and **RecordFrames** are enabled in DReyeVRConfig.ini.
![image](https://user-images.githubusercontent.com/73030394/218316152-22073748-8081-4da1-a3a3-765e17983c09.png)

**Comment by wx983** [comment]
Sorry, my carelessness.
I have found the resulting images in %CARLA_ROOT%\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\FrameCap.
![image](https://user-images.githubusercontent.com/73030394/218317265-0bf921a9-ac07-4972-b494-cc11839d5ae4.png)

But I see the offical document points out it is in Unreal/CarlaUE4/{FrameDir}/{DateTimeNow}/{FrameName}*, [here](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Usage.md#:~:text=Unreal/CarlaUE4/%7BFrameDir%7D/%7BDateTimeNow%7D/%7BFrameName%7D*), although I do see generated images. Images seem to be also produced in %CARLA_ROOT%\Build\UE4Carla\0.9.13-dirty\WindowsNoEditor\CarlaUE4\FrameCap.

**Comment by wx983** [comment]
Great! I totally understand why it is so.

**Comment by GustavoSilvera** [comment]
Yes, sorry the documentation was not clear enough! We'll update it soon. Glad your issue is resolved.
