### ISSUE TITLE
accessability issue

### ISSUE THREAD

**Issue by ande269f** [HARPLab/DReyeVR#87]
Hello 
im trying to set up the system, but have hit a wall when it comes to cloning this:

git clone https://github.com/HARPLab/UnrealEngine -b DReyeVR-0.9.13 --depth 1

In another thread (#83), a response from @GustavoSilvera  said something about needing to request access before cloning. 
Could this be the reason? 
I have done everything else, linking to epic games, downloaded the requered material. 
if this is so, may i get access? 

![kode](https://user-images.githubusercontent.com/114472224/223139061-d6ae39d3-f128-4b3e-8653-4a995bd7d299.JPG)
![Udklip](https://user-images.githubusercontent.com/114472224/223139074-f24f87c9-3024-4f69-adc6-a621c2acf0ba.JPG)

**Comment by GustavoSilvera** [comment]
(For clarity, you'll need to instead clone from [https://github.com/CarlaUnreal/UnrealEngine](https://github.com/CarlaUnreal/UnrealEngine) and follow the `git checkout` instructions I posted to get a compatible UE4 version.
