### ISSUE TITLE
UE4 crash:  Assersion failed: ResourceTableFrameCounter == INDEX_NONE

### ISSUE THREAD

**Issue by ande269f** [HARPLab/DReyeVR#90]
When i'm running "make launch" the unreal engine starts and the windows shows up, starts loading and everything. After about 15 seconds it then crashes with this pop-up: 

![image](https://user-images.githubusercontent.com/114472224/225281745-55b79af9-48d7-48fb-95b6-d73f18b62095.png)

it links to this line in D3D11Texture.cpp: 

![image](https://user-images.githubusercontent.com/114472224/225267968-d6da7864-5ee1-4b40-9359-2a5f488f628d.png)

i found the issue 2 times on the carla git issue page, but on one there was no solution: https://github.com/carla-simulator/carla/issues/6075#issue-1516312584, and on the other, it didnt make any sense to me: https://github.com/carla-simulator/carla/issues/6201#issue-1580627329

no errors happened in the vs2019 console: 

![image](https://user-images.githubusercontent.com/114472224/225272263-647ee837-d2c9-4014-9a7f-3d6cc6564842.png)

**Comment by ande269f** [comment]
Also, we're not having access to any HTC vive pro, but to a HTC vive with pupillabs eyetracking add-on. 
Does this by any chance have supported in SRanipal as well?

**Comment by GustavoSilvera** [comment]
Hm I haven't seen this error before. What version of UnrealEngine are you using? 

Are you using the CarlaUnreal fork of UE4.26, if so, what commit are you on? We mention you should switch the commit of Carla's UE4 fork to this version (d40ec35474e8793b4eea60dba6c4f051186e458e), since they made some changes for 0.9.14 that we don't support yet.

**Comment by GustavoSilvera** [comment]
As for the Pupillabs eye tracking, I'm not sure if they use the SRanipal SDK, but my guess is probably not. Judging by a quick search on [their website](https://docs.pupil-labs.com/vr-ar/developer.html) suggests they have plugins for [Unity](https://github.com/pupil-labs/hmd-eyes) and a localhost connection via [Worldviz](https://docs.worldviz.com/vizard/latest/PupilLabs.htm). SRanipal is specifically designed for the HRC Vive Pro eye, so I doubt it would be compatible. 

But if you add the logic for interfacing with the eye tracking software we'd be happy to merge it in DReyeVR to widen accessibility!

**Comment by ande269f** [comment]
okay, i see that i might be using the wrong branch. I'm a little new to Git, so maybe this is not the right way of doing it.

![image](https://user-images.githubusercontent.com/114472224/225564753-04c2f338-ff14-42e2-9802-746d90d191c7.png)

![image](https://user-images.githubusercontent.com/114472224/225564900-30cee355-299f-43c9-82ed-bbeeea97bea4.png)

I found a way of changing the branch, but only when the branch SHA id shows up with the "git log" command. The d40ec35474e8793b4eea60dba6c4f051186e458e id doesnt show up. Does it mean that i have messed up in one of the first steps? And is it possible to fix now without a re-install of everything?

**Comment by ande269f** [comment]
ahh okay, so its because i did an update.bat at some point, i think that updated my carla from 1.3 to 1.4 Grrr.. 
also, i think i did the git checkout at a wierd, non-sequencial point, which only showed to be a problem now. 

i tried both "git checkout" and "git reset --hard" but it doesn't even recognize the SHA ID (d40ec35474e8793b4eea60dba6c4f051186e458e) at all: 

![image](https://user-images.githubusercontent.com/114472224/225678118-d6b06048-8354-4c2c-8e8f-7d53655481da.png)

**Comment by GustavoSilvera** [comment]
Oh, this is because you cloned the UE4 repository with `--depth 1` which does not keep any history. 

You can restore this history by running `git pull --unshallow` from [here](https://stackoverflow.com/questions/58704510/how-to-get-whole-git-history-afterwards-git-clone-depth-1)

Then try the checkout again.

**Comment by ande269f** [comment]
you're amazing! Thank you so much. 
My editor works now :)

**Comment by LucasFKobernic** [comment]
Hi @GustavoSilvera 

I also changed the branch to the commit: d40ec35474e8793b4eea60dba6c4f051186e458e, but when running the Setup.bat I'm getting the follwing error:

`Failed to download 'http://cdn.unrealengine.com/dependencies/UnrealEngine-12372779-e1515af26c634d2a8ade60b1afd1f065/01bb78539fc8dda386d45f9b5615f9a1e8ca5d94': Der Remoteserver hat einen Fehler zurückgegeben: (403)  (WebException)`.

May is the link not more accessible ?
