### ISSUE TITLE
What does data structure mean in DReyeVR sensor data?

### ISSUE THREAD

**Issue by wx983** [HARPLab/DReyeVR#93]
I can understand  what other data means, but I can't understand them:

![image](https://user-images.githubusercontent.com/73030394/226263391-c6325f9c-3bbc-4554-a6ba-7b20e766bf60.png)
![image](https://user-images.githubusercontent.com/73030394/226263680-417e4e96-6bc1-4ebe-b991-a340168f982e.png)

**Comment by GustavoSilvera** [comment]
Sorry for the lacking explanations. We'll be working on documentation soon.

The `FocusInfo` tracks a struct containing the following (in [DReyeVRData.h](https://github.com/HARPLab/DReyeVR/blob/70a15b5b05b135682cc2daf8ddc4f469e9f9f05c/Carla/Sensor/DReyeVRData.h#L97-L103)):
```c++
TWeakObjectPtr<class AActor> Actor; // pointer to UE4 actor (for internal use)
FVector HitPoint;                   // world-space location of the location of the ray-actor intersection
FVector Normal;                     // normal of the surface at the ray-actor intersection
FString ActorNameTag = "None";      // Tag of the actor being focused on
float Distance;                     // Distance (in meters) the ray traveled until intersecting the actor
bool bDidHit;                       // Whether or not an actor was intersected with the gaze ray
```

And For the EgoVariables we have (also in [DReyeVRData.h](https://github.com/HARPLab/DReyeVR/blob/70a15b5b05b135682cc2daf8ddc4f469e9f9f05c/Carla/Sensor/DReyeVRData.h#L61-L69)):
```c++
// World coordinate Ego vehicle location & rotation
FVector VehicleLocation = FVector::ZeroVector;
FRotator VehicleRotation = FRotator::ZeroRotator;
// Relative Camera position and orientation (for HMD offsets)
FVector CameraLocation = FVector::ZeroVector;
FRotator CameraRotation = FRotator::ZeroRotator;
// Absolute Camera position and orientation (includes vehicle & HMD offset)
FVector CameraLocationAbs = FVector::ZeroVector;
FRotator CameraRotationAbs = FRotator::ZeroRotator;
```

**Comment by wx983** [comment]
@GustavoSilvera OK, I see, but what HMD refers to? Is it the VR helmet?

**Comment by wx983** [comment]
@GustavoSilvera If I want to see these tags, should I change them to `True`? In DReyeVR, they are `false` in default.
![image](https://user-images.githubusercontent.com/73030394/226499976-687c1769-2c9c-4c68-a076-804278d13ef6.png)

**Comment by GustavoSilvera** [comment]
Yes HMD stands for ["Head Mounted Display"](https://en.wikipedia.org/wiki/Head-mounted_display)
