### ISSUE TITLE
How to get Vehicle location（X,Y,Z） of more than EgoVehicle? 

### ISSUE THREAD

**Issue by wx983** [HARPLab/DReyeVR#94]
When generating traffic flow vehicles (they are set into `autopilot`  )，is there any method to record the vehicle location like  EgoVehicle as following?
![image](https://user-images.githubusercontent.com/73030394/226571324-6f93e17b-55ab-435a-bf19-1d032efe7765.png)

**Comment by GustavoSilvera** [comment]
All the other vehicles in the scene (when being recorded) are also tracked in the same recording log file. See the [Carla documentation](https://carla.readthedocs.io/en/latest/ref_recorder_binary_file_format/#packet-6-position).

**Comment by wx983** [comment]
Sorry, I don't really understand it `C:\Users\11\AppData\Local\CarlaUE4\Saved\test.log`, which is a kind of binary file that can't be read by people. Can you guide me more? Should I do something like `show_recorder_file_info.py` to transfer it `test.log`?

**Comment by wx983** [comment]
> 是的，准确地说。有[Carla 文档](https://carla.readthedocs.io/en/latest/adv_recorder/#sample-python-scripts)。

@GustavoSilvera 
Through `manual_control.py` and `start_recording.py -f 111.log -n 50` and `show_recorder_file_info.py -a -f C:\Users\11\AppData\Local\CarlaUE4\Saved\111.log -s 111.txt `, I have obtained 111.txt, which  includes the locations of EgoVehicle and `manual_control` vehicle, but without vehicles generated by `start_recording.py`.
Can you guide me how to acquire the location of vehicles generated by `start_recording.py`?
![image](https://user-images.githubusercontent.com/73030394/227711908-5d3c47ff-f3b9-465c-8830-f0cb3af1534b.png)

**Comment by GustavoSilvera** [comment]
Those vehicles should be tracked in the same file, but if they aren't spawned at the beginning of the file they will probably be spawned later on. Try scrolling down to find them. Look for all the `vehicle.*.*` patterns in the recording file.

**Comment by wx983** [comment]
> Those vehicles should be tracked in the same file, but if they aren't spawned at the beginning of the file they will probably be spawned later on. Try scrolling down to find them. Look for all the `vehicle.*.*` patterns in the recording file.

Thanks, I love you!

**Comment by FBanani** [comment]
@GustavoSilvera 
Hi, I have another question is there any way to measure the miles or km or in other unit that DReyeVR is drived? as well as the location. Because in a curve road it is not practical to get the location!
Thanks
