### ISSUE TITLE
VR and steering wheel issues (VR: Oculus Quest 2, wheel: Formular Force GP)

### ISSUE THREAD

**Issue by ande269f** [HARPLab/DReyeVR#95]
Hi Gustavo
we're having issues when running the DReyeVR program from any possible place (editor, package).
Either the wheel works, or the VR works, but never together: 
VR works in "play" mode, and wheel works in "launch" mode

Software: 
Windows 10 64x
carla 0.9.13 
SteamVR 1.25.6
and the required softare from the guide is all set with the instructed version.

hardware; 
Gforce GTX 2080 Ti
ryzen 5 5600x
Oculus Quest 2
wheel: Formular Force GP

when running in the editor, with the "launch", and when opening the output log, it shows this: 

![image](https://user-images.githubusercontent.com/114472224/227202750-b0925820-cdbc-4bde-a770-2081861ee8a8.png)

and it shows this in the beginning of the errors: 

![image](https://user-images.githubusercontent.com/114472224/227212163-bb1416c7-14e3-402f-b0d0-e2e590f90f6f.png)

but when opening it in "play", the **VR works fine, but the wheel does not do anything**, and no errors show up on the screen, as it usually does when looking for wheel input. 

![image](https://user-images.githubusercontent.com/114472224/227204435-63653dac-02ce-45f3-912b-f27907f3ad5b.png)

my wheel plugin is downloaded, and i have downloaded the driver and GHUB as well 

![image](https://user-images.githubusercontent.com/114472224/227203461-30103c5e-644d-48ce-a5d7-67a47f3ea5e5.png)

and my SteamVR is active during the whole:

![image](https://user-images.githubusercontent.com/114472224/227203806-5e0e54d0-2042-490e-a6ad-4927f3b0c2f7.png)

Do you have a good guess of what is going wrong? 
Thank you for your patience!

**Comment by GustavoSilvera** [comment]
So we always run our VR experiments through the "Play->VR Mode" dropdown in editor, and in package/standalone we run it as `CarlaUE4.exe -vr` (with the `-vr` flag). The logitech steering wheel not working during VR mode is interesting and I'm not immediately sure what is wrong. 

Can you make sure you are on the latest version of DReyeVR (0.1.2 at time of writing)

Can you [enable the logitech logging from the Config file](https://github.com/HARPLab/DReyeVR/blob/70a15b5b05b135682cc2daf8ddc4f469e9f9f05c/Config/DReyeVRConfig.ini#L121) to see some prints. 

I'd also suggest you try to run in package mode with `-vr` and enable the package-mode-logging as we describe [here](https://github.com/HARPLab/DReyeVR/blob/main/Docs/Development.md#1-enable-logging-in-shipping-mode) for further debugging.

Also those BP_Spline errors are benign (just issues with Carla's 0.9.13 Town03 Map) so you can ignore those.

**Comment by ande269f** [comment]
Thank you, both wheel and vr works together now! 
it worked updating the DReyeVR. :) 
We used this guide:
![image](https://user-images.githubusercontent.com/114472224/227959761-4451f579-dc23-41c7-b4bc-411de9ad154c.png)

found on the Installation guide to DReyeVR: https://github.com/HARPLab/DReyeVR/blob/main/Docs/Install.md
